[package]
name = "local-ci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
git2 = "0.18.3"
octocrab = "0.38.0"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
